# Generated by Django 5.0 on 2024-01-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/machine')),
                ('cam_url', models.URLField()),
            ],
            options={
                'verbose_name': 'machine',
                'verbose_name_plural': 'machines',
            },
        ),
        migrations.CreateModel(
            name='GcodeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.ImageField(upload_to='files/gcode')),
                ('radius_cookie', models.IntegerField()),
                ('machine', models.ForeignKey(on_delete=models.SET('Eliminada'), to='zero_points.machine')),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
            },
        ),
    ]
