# Generated by Django 5.0 on 2024-01-03 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zero_points', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcodefile',
            name='file',
            field=models.FileField(upload_to='files/gcode', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gcode', 'txt', 'g'])]),
        ),
    ]
