# Generated by Django 5.0 on 2024-01-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zero_points', '0002_alter_gcodefile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcodefile',
            name='file',
            field=models.FileField(upload_to='files/gcode'),
        ),
    ]
