# Generated by Django 5.0 on 2024-01-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zero_points', '0003_alter_gcodefile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcodefile',
            name='converted_file',
            field=models.FileField(blank=True, default=models.FileField(upload_to='files/gcode/original'), editable=False, null=True, upload_to='files/gcode/converted'),
        ),
        migrations.AddField(
            model_name='machine',
            name='ratio_convertion',
            field=models.FloatField(blank=True, default=2.0, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='x_adj_px_cam',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='y_adj_px_cam',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gcodefile',
            name='file',
            field=models.FileField(upload_to='files/gcode/original'),
        ),
        migrations.AlterField(
            model_name='gcodefile',
            name='radius_cookie',
            field=models.FloatField(),
        ),
    ]
