# Generated by Django 4.2.2 on 2023-08-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.CharField(choices=[('DEV', 'Development'), ('RE', 'Result'), ('EX', 'Example')], default='DEV', max_length=30)),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='img/gallery')),
            ],
            options={
                'verbose_name': 'galeria',
                'verbose_name_plural': 'galerias',
            },
        ),
    ]
