# Generated by Django 5.0 on 2024-01-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'gallery', 'verbose_name_plural': 'galleries'},
        ),
        migrations.AlterModelOptions(
            name='teammate',
            options={'verbose_name': 'teammate', 'verbose_name_plural': 'teammates'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.CharField(max_length=300, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='gallery',
            field=models.CharField(choices=[('DEV', 'development'), ('RE', 'result'), ('EX', 'example')], default='DEV', max_length=30),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='img/gallery', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=40, verbose_name='title'),
        ),
    ]
